name: Check Docs Site

on:
  push:
    branches:
      - "fr/**"

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install
        run: npm ci
      - name: Install Docs
        run: cd docs && npm i
      - name: lint
        run: cd docs && npm run lint
      - name: Build
        run: cd docs && npm run build
      - name: Storybook
        run: cd docs && npm run build-storybook
