name: Run the entire test suite with the latest dependency versions

on:
  schedule:
    - cron: "0 0/8 * * *"
  workflow_dispatch:

jobs:
  test-without-package-lock-json:
    name: Test without package-lock.json
    strategy:
      matrix:
        system: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - name: Delete package-lock.json
        run: "rm package-lock.json"
      - name: Install
        run: npm i
      - name: List dependencies
        run: npm list
      - name: Run tests
        env:
          DO_NOT_SET_THIS_ENV_VAR____IS_HARDHAT_CI: true
          FORCE_COLOR: 3
        run: npm run test || (echo "===== Retry =====" && npm run test)
      - name: Notify failures
        if: failure()
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "workflow_name": "${{ github.workflow }}",
              "run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.GH_ACTION_NOTIFICATIONS_SLACK_WEBHOOK_URL }}
