name: Lint

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: |
            package-lock.json
            docs/package-lock.json
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: lint
        run: npm run lint
      - name: Check dependency versions
        run: node scripts/check-dependencies.js
      - name: Install website
        working-directory: docs/
        run: npm i
      - name: Lint website
        working-directory: docs/
        run: npm run lint
